create table usuarios(

    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    login varchar(100) not null,
    senha varchar(255) not null

--    primary key(id)

);

--CREATE SEQUENCE public.usuarios_id_seq
--    START WITH 1
--    INCREMENT BY 1
--    NO MINVALUE
--    NO MAXVALUE
--    CACHE 1;
--
--    ALTER SEQUENCE public.usuarios_id_seq OWNED BY public.usuarios.id;