create table consultas(

    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    medico_id bigint not null,
    paciente_id bigint not null,
    data timestamp(6) without time zone not null,

--    primary key(id),
    constraint fk_consultas_medico_id foreign key(medico_id) references medicos(id),
    constraint fk_consultas_paciente_id foreign key(paciente_id) references pacientes(id)

);

--CREATE SEQUENCE public.consultas_id_seq
--    START WITH 1
--    INCREMENT BY 1
--    NO MINVALUE
--    NO MAXVALUE
--    CACHE 1;
--
--    ALTER SEQUENCE public.consultas_id_seq OWNED BY public.consultas.id;